[package]
name = "fluent-testing"
version = "0.1.1"
authors = ["Zibi Braniecki <zibi@braniecki.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluent-bundle = { path = "../fluent-bundle" }
fluent-fallback = { path = "../fluent-fallback" }
tokio = { version = "1.0", optional = true, features = ["fs", "rt-multi-thread", "macros", "io-util"] }

[features]
default = ["sync"]
sync = []
async = ["tokio"]
